import type {
  ApplicationRule,
  Card,
  CardBenefit,
  CardCredit,
  CategoryRewardRule,
  SpendCategory,
  TransferPartner,
  WelcomeOffer,
} from "../types";

const VERIFIED = "2025-10-01";

function rule(
  category: SpendCategory,
  multiplier: number,
  rewardType: CategoryRewardRule["rewardType"],
  opts: Partial<Omit<CategoryRewardRule, "category" | "multiplier" | "rewardType">> = {}
): CategoryRewardRule {
  return {
    category,
    multiplier,
    rewardType,
    cap: opts.cap ?? null,
    period: opts.period ?? "permanent",
    restrictions: opts.restrictions,
    onlineOnly: opts.onlineOnly,
    mobileWalletOnly: opts.mobileWalletOnly,
    directBookingOnly: opts.directBookingOnly,
    effectiveFrom: opts.effectiveFrom ?? "2024-01-01",
    effectiveTo: opts.effectiveTo ?? null,
    lastVerifiedAt: opts.lastVerifiedAt ?? VERIFIED,
  };
}

function welcome(
  partial: Omit<WelcomeOffer, "effectiveFrom" | "effectiveTo" | "lastVerifiedAt">
): WelcomeOffer {
  return {
    ...partial,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    lastVerifiedAt: VERIFIED,
  };
}

function credit(
  id: string,
  name: string,
  annualValue: number,
  description: string
): CardCredit {
  return {
    id,
    name,
    annualValue,
    description,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    lastVerifiedAt: VERIFIED,
  };
}

function benefit(
  id: string,
  name: string,
  category: string,
  estimatedAnnualValue: number,
  description: string
): CardBenefit {
  return {
    id,
    name,
    category,
    estimatedAnnualValue,
    description,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    lastVerifiedAt: VERIFIED,
  };
}

function appRule(
  id: string,
  issuer: string,
  description: string,
  ruleKey: ApplicationRule["ruleKey"] | undefined,
  opts: {
    details?: string;
    sourceType: ApplicationRule["sourceType"];
    confidence: ApplicationRule["confidence"];
    sourceUrl?: string;
    explanatoryText?: string;
  }
): ApplicationRule {
  return {
    id,
    issuer,
    description,
    ruleKey,
    details: opts.details,
    sourceType: opts.sourceType,
    confidence: opts.confidence,
    sourceUrl: opts.sourceUrl,
    explanatoryText: opts.explanatoryText,
    lastVerifiedAt: VERIFIED,
  };
}

const CHASE_5_24 = appRule(
  "chase-5-24",
  "Chase",
  "Chase may deny if 5+ personal cards opened in 24 months",
  "5_24",
  {
    sourceType: "community_reported",
    confidence: "medium",
    explanatoryText:
      "Widely reported issuer policy; Chase does not publish an official 5/24 rule page.",
  }
);

const ONE_SAPPHIRE = appRule(
  "chase-one-sapphire",
  "Chase",
  "Only one Sapphire-branded card at a time",
  "one_sapphire",
  {
    sourceType: "issuer_help",
    confidence: "high",
    sourceUrl: "https://www.chase.com",
    explanatoryText: "Documented in Chase product terms and help materials.",
  }
);

const AMEX_ONCE = appRule(
  "amex-welcome-once",
  "American Express",
  "Welcome offers typically once per lifetime per product",
  "welcome_once",
  {
    sourceType: "issuer_published",
    confidence: "high",
    sourceUrl: "https://www.americanexpress.com",
    explanatoryText: "Amex publishes once-per-lifetime welcome offer language.",
  }
);

const UR_PARTNERS: TransferPartner[] = [
  { name: "United", type: "airline", transferRatio: "1:1" },
  { name: "Hyatt", type: "hotel", transferRatio: "1:1" },
  { name: "Southwest", type: "airline", transferRatio: "1:1" },
];

export const CARD_DATABASE: Card[] = [
  {
    id: "chase-sapphire-preferred",
    issuer: "Chase",
    cardName: "Sapphire Preferred",
    cardNetwork: "visa",
    annualFee: 95,
    foreignTransactionFee: 0,
    baseRewardRate: 1,
    rewardCurrency: "Ultimate Rewards",
    rewardProgram: "Ultimate Rewards",
    welcomeOffer: welcome({
      description: "60,000 bonus points after $5,000 spend in 3 months",
      bonusAmount: 60000,
      bonusType: "points",
      spendRequirement: 5000,
      timeWindowMonths: 3,
      estimatedValue: 900,
    }),
    categoryRewards: [
      rule("dining", 3, "points"),
      rule("streaming", 3, "points"),
      rule("online", 3, "points", { restrictions: ["Excludes groceries, travel"] }),
      rule("travel", 5, "points", { directBookingOnly: true }),
    ],
    credits: [],
    benefits: [
      benefit(
        "csp-travel-credit",
        "Annual travel credit",
        "travel",
        50,
        "$50 hotel credit via Chase Travel"
      ),
    ],
    transferPartners: UR_PARTNERS,
    applicationRules: [CHASE_5_24, ONE_SAPPHIRE],
    productFamily: "sapphire",
    businessOrPersonal: "personal",
    complexity: "moderate",
    hasLounge: false,
    hasHotelBenefits: true,
    hasAirlineBenefits: false,
    tags: ["travel", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["chase.com"],
    active: true,
  },
  {
    id: "chase-sapphire-reserve",
    issuer: "Chase",
    cardName: "Sapphire Reserve",
    cardNetwork: "visa",
    annualFee: 550,
    foreignTransactionFee: 0,
    baseRewardRate: 1,
    rewardCurrency: "Ultimate Rewards",
    rewardProgram: "Ultimate Rewards",
    welcomeOffer: welcome({
      description: "60,000 bonus points after $5,000 spend in 3 months",
      bonusAmount: 60000,
      bonusType: "points",
      spendRequirement: 5000,
      timeWindowMonths: 3,
      estimatedValue: 900,
    }),
    categoryRewards: [
      rule("travel", 8, "points", { directBookingOnly: true }),
      rule("flights", 4, "points"),
      rule("hotels", 4, "points"),
      rule("dining", 3, "points"),
    ],
    credits: [
      credit(
        "csr-travel",
        "Travel credit",
        300,
        "$300 annual travel credit"
      ),
    ],
    benefits: [
      benefit(
        "csr-lounge",
        "Priority Pass",
        "lounge",
        400,
        "Priority Pass Select membership"
      ),
    ],
    transferPartners: UR_PARTNERS,
    applicationRules: [CHASE_5_24, ONE_SAPPHIRE],
    productFamily: "sapphire",
    businessOrPersonal: "personal",
    complexity: "advanced",
    hasLounge: true,
    hasHotelBenefits: true,
    hasAirlineBenefits: true,
    tags: ["travel", "premium", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["chase.com"],
    active: true,
  },
  {
    id: "chase-freedom-unlimited",
    issuer: "Chase",
    cardName: "Freedom Unlimited",
    cardNetwork: "visa",
    annualFee: 0,
    foreignTransactionFee: 3,
    baseRewardRate: 1.5,
    rewardCurrency: "Ultimate Rewards",
    rewardProgram: "Ultimate Rewards",
    welcomeOffer: welcome({
      description: "$200 bonus after $500 spend in 3 months",
      bonusAmount: 200,
      bonusType: "cash",
      spendRequirement: 500,
      timeWindowMonths: 3,
      estimatedValue: 200,
    }),
    categoryRewards: [
      rule("dining", 3, "points"),
      rule("drugstores", 3, "points"),
      rule("travel", 5, "points", { directBookingOnly: true }),
    ],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [CHASE_5_24],
    productFamily: "freedom",
    businessOrPersonal: "personal",
    complexity: "simple",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["no_fee", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["chase.com"],
    active: true,
  },
  {
    id: "chase-freedom-flex",
    issuer: "Chase",
    cardName: "Freedom Flex",
    cardNetwork: "mastercard",
    annualFee: 0,
    foreignTransactionFee: 3,
    baseRewardRate: 1,
    rewardCurrency: "Ultimate Rewards",
    rewardProgram: "Ultimate Rewards",
    welcomeOffer: welcome({
      description: "$200 bonus after $500 spend in 3 months",
      bonusAmount: 200,
      bonusType: "cash",
      spendRequirement: 500,
      timeWindowMonths: 3,
      estimatedValue: 200,
    }),
    categoryRewards: [
      rule("dining", 3, "points"),
      rule("drugstores", 3, "points"),
      rule("travel", 5, "points", { directBookingOnly: true }),
      rule("groceries", 5, "points", {
        cap: 1500,
        period: "quarterly",
        restrictions: ["Rotating / quarterly activation"],
      }),
    ],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [CHASE_5_24],
    productFamily: "freedom",
    businessOrPersonal: "personal",
    complexity: "moderate",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["no_fee", "rotating", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["chase.com"],
    active: true,
  },
  {
    id: "amex-gold",
    issuer: "American Express",
    cardName: "Gold Card",
    cardNetwork: "amex",
    annualFee: 250,
    foreignTransactionFee: 0,
    baseRewardRate: 1,
    rewardCurrency: "Membership Rewards",
    rewardProgram: "Membership Rewards",
    welcomeOffer: welcome({
      description: "60,000 Membership Rewards after $6,000 in 6 months",
      bonusAmount: 60000,
      bonusType: "points",
      spendRequirement: 6000,
      timeWindowMonths: 6,
      estimatedValue: 1200,
    }),
    categoryRewards: [
      rule("dining", 4, "points"),
      rule("groceries", 4, "points", { cap: 25000, period: "annual" }),
    ],
    credits: [
      credit("gold-dining", "Dining credit", 120, "$10/month dining partners"),
      credit("gold-uber", "Uber Cash", 120, "$10/month Uber Cash"),
    ],
    benefits: [],
    transferPartners: [
      { name: "Delta", type: "airline", transferRatio: "1:1" },
      { name: "Marriott", type: "hotel", transferRatio: "1:1" },
    ],
    applicationRules: [AMEX_ONCE],
    productFamily: "amex-gold",
    businessOrPersonal: "personal",
    complexity: "moderate",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["dining", "groceries", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["americanexpress.com"],
    active: true,
  },
  {
    id: "amex-platinum",
    issuer: "American Express",
    cardName: "Platinum Card",
    cardNetwork: "amex",
    annualFee: 695,
    foreignTransactionFee: 0,
    baseRewardRate: 1,
    rewardCurrency: "Membership Rewards",
    rewardProgram: "Membership Rewards",
    welcomeOffer: welcome({
      description: "80,000 points after $8,000 spend in 6 months",
      bonusAmount: 80000,
      bonusType: "points",
      spendRequirement: 8000,
      timeWindowMonths: 6,
      estimatedValue: 1600,
    }),
    categoryRewards: [
      rule("flights", 5, "points", {
        directBookingOnly: true,
        restrictions: ["Airlines or Amex Travel"],
      }),
      rule("hotels", 5, "points", { directBookingOnly: true }),
    ],
    credits: [
      credit("plat-airline", "Airline fee credit", 200, "Select airline incidentals"),
      credit("plat-hotel", "Hotel credit", 200, "Fine Hotels + Resorts"),
      credit("plat-uber", "Uber Cash", 200, "$15/month Uber"),
    ],
    benefits: [
      benefit(
        "plat-lounge",
        "Centurion + Priority Pass",
        "lounge",
        500,
        "Airport lounge access"
      ),
    ],
    transferPartners: [
      { name: "Delta", type: "airline", transferRatio: "1:1" },
      { name: "Hilton", type: "hotel", transferRatio: "1:2" },
    ],
    applicationRules: [AMEX_ONCE],
    productFamily: "amex-platinum",
    businessOrPersonal: "personal",
    complexity: "advanced",
    hasLounge: true,
    hasHotelBenefits: true,
    hasAirlineBenefits: true,
    tags: ["travel", "premium", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["americanexpress.com"],
    active: true,
  },
  {
    id: "amex-blue-cash-preferred",
    issuer: "American Express",
    cardName: "Blue Cash Preferred",
    cardNetwork: "amex",
    annualFee: 95,
    foreignTransactionFee: 2.7,
    baseRewardRate: 1,
    rewardCurrency: "USD",
    rewardProgram: "Cash Back",
    welcomeOffer: welcome({
      description: "$250 statement credit after $3,000 in 6 months",
      bonusAmount: 250,
      bonusType: "statement_credit",
      spendRequirement: 3000,
      timeWindowMonths: 6,
      estimatedValue: 250,
    }),
    categoryRewards: [
      rule("groceries", 6, "cashback", { cap: 6000, period: "annual" }),
      rule("streaming", 6, "cashback"),
      rule("transit", 3, "cashback"),
      rule("gas", 3, "cashback"),
    ],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [AMEX_ONCE],
    productFamily: "blue-cash",
    businessOrPersonal: "personal",
    complexity: "simple",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["cashback", "groceries"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["americanexpress.com"],
    active: true,
  },
  {
    id: "citi-double-cash",
    issuer: "Citi",
    cardName: "Double Cash",
    cardNetwork: "mastercard",
    annualFee: 0,
    foreignTransactionFee: 3,
    baseRewardRate: 2,
    rewardCurrency: "USD",
    rewardProgram: "Cash Back",
    welcomeOffer: null,
    categoryRewards: [],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [],
    productFamily: "double-cash",
    businessOrPersonal: "personal",
    complexity: "simple",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["cashback", "no_fee", "catchall"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["citi.com"],
    active: true,
  },
  {
    id: "citi-custom-cash",
    issuer: "Citi",
    cardName: "Custom Cash",
    cardNetwork: "mastercard",
    annualFee: 0,
    foreignTransactionFee: 3,
    baseRewardRate: 1,
    rewardCurrency: "USD",
    rewardProgram: "Cash Back",
    welcomeOffer: welcome({
      description: "$200 after $1,500 spend in 6 months",
      bonusAmount: 200,
      bonusType: "statement_credit",
      spendRequirement: 1500,
      timeWindowMonths: 6,
      estimatedValue: 200,
    }),
    categoryRewards: [
      rule("dining", 5, "cashback", {
        cap: 500,
        period: "monthly",
        restrictions: ["Top eligible spend category each cycle"],
      }),
      rule("groceries", 5, "cashback", {
        cap: 500,
        period: "monthly",
        restrictions: ["Top eligible spend category each cycle"],
      }),
      rule("gas", 5, "cashback", {
        cap: 500,
        period: "monthly",
        restrictions: ["Top eligible spend category each cycle"],
      }),
      rule("streaming", 5, "cashback", {
        cap: 500,
        period: "monthly",
        restrictions: ["Top eligible spend category each cycle"],
      }),
    ],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [],
    productFamily: "custom-cash",
    businessOrPersonal: "personal",
    complexity: "moderate",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["cashback", "no_fee"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["citi.com"],
    active: true,
  },
  {
    id: "capone-venture-x",
    issuer: "Capital One",
    cardName: "Venture X",
    cardNetwork: "visa",
    annualFee: 395,
    foreignTransactionFee: 0,
    baseRewardRate: 2,
    rewardCurrency: "Capital One Miles",
    rewardProgram: "Capital One Miles",
    welcomeOffer: welcome({
      description: "75,000 miles after $4,000 in 3 months",
      bonusAmount: 75000,
      bonusType: "miles",
      spendRequirement: 4000,
      timeWindowMonths: 3,
      estimatedValue: 1125,
    }),
    categoryRewards: [
      rule("travel", 10, "miles", { directBookingOnly: true }),
      rule("hotels", 10, "miles", { directBookingOnly: true }),
      rule("flights", 5, "miles"),
    ],
    credits: [
      credit("vx-travel", "Travel credit", 300, "$300 Capital One Travel credit"),
      credit("vx-anniversary", "Anniversary miles", 100, "10,000 anniversary miles"),
    ],
    benefits: [
      benefit(
        "vx-lounge",
        "Capital One Lounges + Priority Pass",
        "lounge",
        350,
        "Lounge access"
      ),
    ],
    transferPartners: [
      { name: "Air Canada", type: "airline", transferRatio: "1:1" },
      { name: "Turkish", type: "airline", transferRatio: "1:1" },
    ],
    applicationRules: [],
    productFamily: "venture",
    businessOrPersonal: "personal",
    complexity: "moderate",
    hasLounge: true,
    hasHotelBenefits: true,
    hasAirlineBenefits: true,
    tags: ["travel", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["capitalone.com"],
    active: true,
  },
  {
    id: "capone-savor",
    issuer: "Capital One",
    cardName: "Savor",
    cardNetwork: "mastercard",
    annualFee: 0,
    foreignTransactionFee: 0,
    baseRewardRate: 1,
    rewardCurrency: "USD",
    rewardProgram: "Cash Back",
    welcomeOffer: welcome({
      description: "$200 after $500 spend in 3 months",
      bonusAmount: 200,
      bonusType: "cash",
      spendRequirement: 500,
      timeWindowMonths: 3,
      estimatedValue: 200,
    }),
    categoryRewards: [
      rule("dining", 3, "cashback"),
      rule("groceries", 3, "cashback"),
      rule("streaming", 3, "cashback"),
    ],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [],
    productFamily: "savor",
    businessOrPersonal: "personal",
    complexity: "simple",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["cashback", "dining", "no_fee"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["capitalone.com"],
    active: true,
  },
  {
    id: "discover-it",
    issuer: "Discover",
    cardName: "it Cash Back",
    cardNetwork: "discover",
    annualFee: 0,
    foreignTransactionFee: 0,
    baseRewardRate: 1,
    rewardCurrency: "Discover Cashback",
    rewardProgram: "Cashback Match",
    welcomeOffer: welcome({
      description: "Cashback Match first year",
      bonusAmount: 0,
      bonusType: "cashback",
      spendRequirement: 0,
      timeWindowMonths: 12,
      estimatedValue: 200,
    }),
    categoryRewards: [
      rule("groceries", 5, "cashback", {
        cap: 1500,
        period: "quarterly",
        restrictions: ["Rotating categories — activation required"],
      }),
    ],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [],
    productFamily: "discover-it",
    businessOrPersonal: "personal",
    complexity: "moderate",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["cashback", "no_fee", "rotating"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["discover.com"],
    active: true,
  },
  {
    id: "wells-active-cash",
    issuer: "Wells Fargo",
    cardName: "Active Cash",
    cardNetwork: "visa",
    annualFee: 0,
    foreignTransactionFee: 3,
    baseRewardRate: 2,
    rewardCurrency: "USD",
    rewardProgram: "Cash Back",
    welcomeOffer: welcome({
      description: "$200 after $500 spend in 3 months",
      bonusAmount: 200,
      bonusType: "cash",
      spendRequirement: 500,
      timeWindowMonths: 3,
      estimatedValue: 200,
    }),
    categoryRewards: [],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [],
    productFamily: "active-cash",
    businessOrPersonal: "personal",
    complexity: "simple",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["cashback", "no_fee", "catchall"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["wellsfargo.com"],
    active: true,
  },
  {
    id: "bilt-mastercard",
    issuer: "Bilt",
    cardName: "Mastercard",
    cardNetwork: "mastercard",
    annualFee: 0,
    foreignTransactionFee: 0,
    baseRewardRate: 1,
    rewardCurrency: "Bilt Points",
    rewardProgram: "Bilt Rewards",
    welcomeOffer: null,
    categoryRewards: [
      rule("dining", 3, "points"),
      rule("travel", 2, "points"),
      rule("rent", 1, "points", {
        restrictions: ["Must use Bilt app — no fee rent payments"],
      }),
    ],
    credits: [],
    benefits: [],
    transferPartners: [
      { name: "Hyatt", type: "hotel", transferRatio: "1:1" },
      { name: "United", type: "airline", transferRatio: "1:1" },
    ],
    applicationRules: [],
    productFamily: "bilt",
    businessOrPersonal: "personal",
    complexity: "moderate",
    hasLounge: false,
    hasHotelBenefits: true,
    hasAirlineBenefits: true,
    tags: ["rent", "travel", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["biltrewards.com"],
    active: true,
  },
  {
    id: "usbank-altitude-go",
    issuer: "U.S. Bank",
    cardName: "Altitude Go",
    cardNetwork: "visa",
    annualFee: 0,
    foreignTransactionFee: 3,
    baseRewardRate: 1,
    rewardCurrency: "Cash Miles",
    rewardProgram: "Altitude Rewards",
    welcomeOffer: welcome({
      description: "20,000 points after $1,000 in 90 days",
      bonusAmount: 20000,
      bonusType: "points",
      spendRequirement: 1000,
      timeWindowMonths: 3,
      estimatedValue: 300,
    }),
    categoryRewards: [
      rule("dining", 4, "points"),
      rule("groceries", 2, "points"),
      rule("streaming", 2, "points"),
      rule("gas", 2, "points"),
    ],
    credits: [],
    benefits: [],
    transferPartners: [],
    applicationRules: [],
    productFamily: "altitude-go",
    businessOrPersonal: "personal",
    complexity: "simple",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["dining", "no_fee"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["usbank.com"],
    active: true,
  },
  {
    id: "chase-ink-business-cash",
    issuer: "Chase",
    cardName: "Ink Business Cash",
    cardNetwork: "visa",
    annualFee: 0,
    foreignTransactionFee: 3,
    baseRewardRate: 1,
    rewardCurrency: "Ultimate Rewards",
    rewardProgram: "Ultimate Rewards",
    welcomeOffer: welcome({
      description: "$750 cash back after $6,000 spend in 3 months",
      bonusAmount: 750,
      bonusType: "cash",
      spendRequirement: 6000,
      timeWindowMonths: 3,
      estimatedValue: 750,
    }),
    categoryRewards: [
      rule("online", 5, "points", { cap: 25000, period: "annual" }),
      rule("utilities", 5, "points", { cap: 25000, period: "annual" }),
      rule("mobile_wallet", 5, "points", { cap: 25000, period: "annual" }),
    ],
    credits: [],
    benefits: [],
    transferPartners: UR_PARTNERS,
    applicationRules: [CHASE_5_24],
    productFamily: "ink",
    businessOrPersonal: "business",
    complexity: "moderate",
    hasLounge: false,
    hasHotelBenefits: false,
    hasAirlineBenefits: false,
    tags: ["business", "flexible_points"],
    lastVerifiedAt: VERIFIED,
    sourceReferences: ["chase.com"],
    active: true,
  },
];

export function getCardById(id: string): Card | undefined {
  return CARD_DATABASE.find((c) => c.id === id);
}

export function getActiveCards(catalog: Card[] = CARD_DATABASE): Card[] {
  return catalog.filter((c) => c.active);
}
